### ISSUE TITLE
pypi

### ISSUE THREAD

**Issue by eggplants** [toritamantaro/yaml_cv_py#1]
pypiへの登録をしていただけると助かります。

要pypiユーザ登録ですが、以下の2つのファイルを追加した上で、Secretsに`PYPI_USERNAME`及び`PYPI_PASSWORD`を記述し、ローカルから`git tag <version> && git push --tags`するとreleaseされます。
`pip install yaml-cv-py # またはpip install yaml_cv_py`だけで`make_cv.py`できるようになると便利なので…

`setup.py`:

```python
from setuptools import find_packages, setup  # type: ignore

setup(
    name='yaml-cv-py',
    version='0.0.1',
    description='YAMLによる履歴書作成スクリプト',
    description_content_type='',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/toritamantaro/yaml_cv_py',
    author='toritamantaro',
    packages=find_packages(),
    python_requires='>=3.8',
    include_package_data=True,
    license='MIT',
    install_requires=[ # requirements.txtに記述し読込でも良
        'PyYAML==5.4.1',
        'reprotlab==3.5.59'
    ],
    scripts=['make_cv.py']
)
```

`.github/workflows/release.yml`:

```yml
name: Release Package

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
          draft: false
          prerelease: false
  pypi:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
```
